# Generated by Django 5.1.5 on 2025-04-15 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Fire'), (2, 'Water'), (3, 'Electric'), (4, 'Grass'), (5, 'Ice'), (6, 'Fighting'), (7, 'Poison'), (8, 'Ground'), (9, 'Flying'), (10, 'Psychic'), (11, 'Bug'), (12, 'Rock'), (13, 'Ghost'), (14, 'Dragon')])),
                ('category', models.IntegerField(choices=[(0, 'Physical'), (1, 'Special'), (2, 'Status')])),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('powerpoints', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(64)])),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pokemon_image_url', models.URLField(blank=True)),
                ('level', models.IntegerField(help_text='Level must be between 1 and 99', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('type1', models.IntegerField(choices=[(0, 'Normal'), (1, 'Fire'), (2, 'Water'), (3, 'Electric'), (4, 'Grass'), (5, 'Ice'), (6, 'Fighting'), (7, 'Poison'), (8, 'Ground'), (9, 'Flying'), (10, 'Psychic'), (11, 'Bug'), (12, 'Rock'), (13, 'Ghost'), (14, 'Dragon')])),
                ('type2', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Fire'), (2, 'Water'), (3, 'Electric'), (4, 'Grass'), (5, 'Ice'), (6, 'Fighting'), (7, 'Poison'), (8, 'Ground'), (9, 'Flying'), (10, 'Psychic'), (11, 'Bug'), (12, 'Rock'), (13, 'Ghost'), (14, 'Dragon')], null=True)),
                ('hit_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('special', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('accuracy', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('evasiveness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('move1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move1', to='project.move')),
                ('move2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move2', to='project.move')),
                ('move3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move3', to='project.move')),
                ('move4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move4', to='project.move')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('pokemon_region', models.TextField(blank=True)),
                ('pokemon_town', models.TextField(blank=True)),
                ('trainer_image_url', models.URLField(blank=True)),
                ('rival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon1', to='project.pokemon_species')),
                ('pokemon2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon2', to='project.pokemon_species')),
                ('pokemon3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon3', to='project.pokemon_species')),
                ('pokemon4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon4', to='project.pokemon_species')),
                ('pokemon5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon5', to='project.pokemon_species')),
                ('pokemon6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon6', to='project.pokemon_species')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.trainer')),
            ],
        ),
    ]
